



server:
  port: 8888

  

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
    
  routes:
    cart-service:
      path: /cart/**
      service-id: cart-service
      strip-prefix: false
    
    menu-item-service:
      path: /menu-item/**
      service-id: menu-item-service
      strip-prefix: false
      
    coupon-service:
      path: /coupons/**
      service-id: coupon-service
      strip-prefix: false
      
      
    